query getCurrentUserTweets($identity: String!,$count: Int!,$access_token: String!,$access_secret: String!) {
        getTimeline(identifier:user_id, identity:$identity,count:$count,
        access_token: $access_token,
        access_token_secret: $access_secret)
        {
            created_at
            id_str
            full_text
            in_reply_to_status_id_str
        }
  }