query getTaggedTweets($queryText: String!,$limit: Int!) {
      search(query: $queryText,count: $limit){
        created_at
        id_str
        full_text
        in_reply_to_status_id_str
      }
  }