query twitter($idstr: String!) @client{
      user (identifier: user_id, value: $idstr) {
        created_at
        description
        id_str
        screen_name
        name
        profile_image_url_https
    }
}