query fetchTweets($query: String!,$tweetSize: Int!) @client{
    twitter{
      search(q: $query result_type:recent,count:$tweetSize){
        id_str
        created_at
        text
        user{
          id_str
          name
          screen_name
          description
          profile_image_url
          tweets_count
          followers_count
        }
      }
    }
  }