query tweets{
    twitter{
      search(q:"@cnni" result_type:popular,count:20){
        id_str
        created_at
        text
        user{
          id_str
          created_at
          name
          description
          screen_name
          profile_image_url
          tweets_count
        }
      }
    }
  }